# Generated by Django 4.1.4 on 2023-01-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='Tarifs',
            new_name='Tarif',
        ),
    ]
