# Generated by Django 4.1.4 on 2023-01-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_services_service_rename_tarifs_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='prix',
            field=models.CharField(max_length=20),
        ),
    ]
